-- GPIOS
GPIO_LED = 7
GPIO_SWITCH = 6

-- WiFi
WIFI_SSID = "YOUR_SSID"
WIFI_PASS = "YOUR PASSWORD"

-- Alarms
WIFI_ALARM_ID = 0
WIFI_LED_BLINK_ALARM_ID = 1

-- MQTT
MQTT_CLIENTID = "plugxxx"
MQTT_HOST = "YOUR_HOST"
MQTT_PORT = 1883
MQTT_MAINTOPIC = "YOUT MQTT_TOPIC" .. MQTT_CLIENTID

-- Confirmation message
print("\nGlobal variables loaded...\n")
